#backend:
#  name: github
#  repo: PuReWebDev/mpdemo # Path to your GitHub repository
backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: uploads/img
public_folder: /img

collections:
- name: "mainPages"
  label: "Main Pages and Settings"
  create: true
  files:
  - file: "src/pages/index.md"
    label: "Home"
    name: "home"
    fields:
    - {
      label: "Template Key",
      name: "templateKey",
      widget: "hidden",
      default: "home-page",
    }
    - {
      label: "Title",
      name: "title",
      widget: "string",
    }
    - {
      label: "Content Section One",
      name: "content_section_one",
      widget: string,
    }
    - label: "Panel Content"
      name: "panel_content"
      widget: "list"
      fields:
        - {label: Panel Link, name: panel_content_link, widget: string, default: "Panel Content"}
    - label: "Header Slide"
      name: "header_slide"
      widget: "list"
      fields:
        - {label: Panel Link, name: panel_link, widget: string, default: "Panel Link"}
        - {label: Panel Image, name: panel_image, widget: image, default: "/img/gamecap.jpg"}
    - label: "Footer Slide"
      name: "header_slide"
      widget: "list"
      fields:
        - {label: Footer Text, name: footer_text, widget: markdown, default: "Panel Link"}
        - {label: Footer Image, name: footer_image, widget: image, default: "/img/gamecap.jpg"}    
  - file: "src/pages/config.md"
    label: "Global Settings"
    name: "config"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "hidden-page",
      }
      - { label: Site Title, name: title, widget: "string" }
      - { label: Site Description, name: desc, widget: "string" }
      - {
        label: Menu,
        name: menu_nav,
        widget: list,
        fields:
          [
          { label: Text, name: text, widget: string },
          { label: URL, name: url, widget: string },
          ]
      }
- name: "content"
  label: "Content Pages"
  folder: "src/pages/content"
  create: true
  fields:
  - { label: "Title", name: "title", widget: "string" }
  - { label: "Description", name: "description", widget: "text" }
  - { label: "Body", name: "body", widget: "markdown" }

  
