backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder_relative: false
site_url: localhost:8000
media_folder: static/assets
public_folder: assets

collections:
- name: "mainPages"
  label: "Main Pages and Settings"
  media_library:
    config:
      multiple: true

  create: false
  files:
  - file: "src/pages/index.md"
    label: "Home"
    name: "home"
    fields:
    - {
      label: "Template Key",
      name: "templateKey",
      widget: "hidden",
      default: "home-page",
    }
    - {
      label: "Title",
      name: "title",
      widget: "string",
    }
    - {
      label: "Content Section One",
      name: "content_section_one",
      widget: string,
    }
    - label: "Panel Content"
      name: "panel_content"
      widget: "list"
      fields:
        - {label: Panel Link, name: panel_content_link, widget: string, default: "Panel Content"}
    - label: "Header Slide"
      name: "header_slide"
      widget: "list"
      fields:
        - {label: Header Link, name: header_link, widget: string, default: "Panel Link"}
        - {label: Header Link Key, name: header_link_key, widget: string}
        - {label: Header Image, name: header_image, widget: image}
    - label: "Footer Slide"
      name: "footer_slide"
      widget: "list"
      fields:
        - {label: Footer Logo, name: footer_logo, widget: image}
        - {label: Footer Image, name: footer_image, widget: image}
        - {label: Footer Content, name: footer_content, widget: markdown}
        - {label: Footer Color, name: footer_color, widget: string}
        - {label: Signature, name: footer_signature, widget: string}    
  - file: "src/pages/config.md"
    label: "Global Settings"
    name: "config"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "hidden-page",
      }
      - { label: Site Title, name: title, widget: "string" }
      - { label: Site Description, name: desc, widget: "string" }
  - file: "src/pages/navigation.md"
    label: "Navigation"
    name: "navigation"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "hidden-page",
      }
      - {
        label: Main Menu,
        name: menu_nav,
        widget: list,
        fields:
          [
          { label: Text, name: text, widget: string },
          { label: URL, name: url, widget: string },
          ]
      }
      - {
        label: Dropdowns,
        name: dropdowns,
        required: false,
        widget: list,
        fields:
          [
          { label: Dropdown Title, name: dropdown_title, widget: string },
          {
            label: Dropdown Items,
            name: dropdown_items,
            widget: list,
            fields: 
              [
                { label: Text, name: text, widget: string },
                { label: URL, name: url, widget: string },
              ]
          }
          ]
      }
      - { label: Footer Logo, name: footer_logo, widget: image, required: false }
      - {
        label: Footer Left Links,
        name: footer_nav_left,
        widget: list,
        fields:
          [
          { label: Text, name: text, widget: string },
          { label: URL, name: url, widget: string, required: false },
          ]
      }
      - {
        label: Footer Right Links,
        name: footer_nav_right,
        widget: list,
        fields:
          [
          { label: Text, name: text, widget: string },
          { label: URL, name: url, widget: string, required: false },
          { label: or Download, name: download, widget: file, required: false }
          ]
      }
- name: "about"
  label: "About Us"
  identifier_field: title
  files:
  - file: "src/pages/about/index.md"
    label: "About Us Page"
    name: "about_us"
    fields:
      - { label: "Template Key", name: "templateKey",widget: "hidden", default: "about-page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Quote", name: "quote", widget: "text" }
      - { label: "Signature", name: "signature_widget", widget: "string" }
      - { label: "Left Panel Title", name: "left_panel_title", widget: "string" }
      - { label: "Left Panel Content", name: "left_panel_content", widget: "string" }
      - label: "Right Panel Row"
        name: "right_panel_row"
        widget: "list"
        fields:
          - label: "Right Panel Stats"
            name: "right_panel_stats"
            widget: "list"
            fields: 
                - { label: "Panel Number", name: "panel_number", valueType: "int", min: 1, step: 1 }
                - { label: "Panel Label" , name: "panel_label", widget: "string" }
                - { label: "Green Plus", name: "green_plus", widget: "boolean", default: false }
- name: "teammembers"
  label: "Team Pages"
  folder: "src/pages/member"
  identifier_field: title
  create: true
  fields:
    - {
      label: "Template Key",
      name: "templateKey",
      widget: "hidden",
      default: "team-member-page",
    }
    - {label: Title, name: title, widget: string }
    - {label: Team Members Position, name: team_position, widget: string, default: "partner"}
    - {label: Team Members Name, name: team_member_name, widget: string, default: "John Doe"}
    - {label: Team Member Image, name: team_member_image, widget: image }
    - {label: Facebook, name: facebook_link, widget: string }
    - {label: Monster, name: monster_link, widget: string }
    - {label: Linkedin, name: linkedin_link, widget: string }
    - label: "Current Projects"
      name: "current_projects"
      widget: "list"
      fields: 
          - {label: Project Name, name: project_name, widget: string }
          - {label: Project Link, name: project_link, widget: string } 
    - label: "Previous Projects"
      name: "previous_projects"
      widget: "list"
      fields: 
          - {label: Project Name, name: project_name, widget: string }
          - {label: Project Link, name: project_link, widget: string }   
    - {label: Bio, name: bio, widget: text }
    - label: "Experience"
      name: "experience"
      widget: "list"
      fields: 
          - {label: Position Location, name: position_location, widget: string }
          - {label: Position Title, name: position_title, widget: string }
    - label: "Education"
      name: "education"
      widget: "list"
      fields: 
          - {label: School Name, name: school_name, widget: string }
          - {label: Degree Earned, name: degree, widget: string }
- name: "portfolio"
  label: "Portfolio"
  identifier_field: title
  files:
  - file: "src/pages/portfolio/index.md"
    label: "Portfolio Page"
    name: "portfolio"
    fields:
    - {
      label: "Template Key",
      name: "templateKey",
      widget: "hidden",
      default: "portfolio-page",
    }
    - label: "Title"
      name: "title"
      widget: "string"
    - label: "Panel"
      name: "panel"
      widget: "list"
      fields:
        - {label: Panel Title, name: panel_title, widget: string, default: "Panel Title"}
        - {label: "Menu Key", name: "menu_key", widget: "string"}
        - label: "Panel Images"
          name: "panel_images"
          widget: "list"
          fields:
          - {label: Title, name: panel_title, widget: string}
          - {label: Panel Image, name: panel_image, widget: image}
          - {label: Panel Alt, name: panel_image_alt, widget: image}
          - {label: Panel Description, name: panel_description, widget: string}
- name: teamlist
  label: Team
  slug: "/team"
  files:
  - file: "src/pages/team/index.md"
    label: Team Page Configuration
    name: teamlist_member
    fields: 
    - {
      label: "Template Key",
      name: "templateKey",
      widget: "hidden",
      default: "team-page",
    }
    - { label: Team Member List Title, name: team_member_title, widget: string } 
    - { label: Team Member List Sub Title, name: team_member_subtitle_title, widget: string } 
- name: "contact"
  label: "Contact"
  identifier_field: title
  files:
  - file: "src/pages/contact/index.md"
    label: "Contact Page"
    name: "contact"
    fields:
    - {
      label: "Template Key",
      name: "templateKey",
      widget: "hidden",
      default: "contact-page",
    }
    - label: "Title"
      name: "title"
      widget: "string"
    - label: "Sub Title"
      name: "sub_title"
      widget: "string"
    - label: "Contact Panel"
      name: "contact_panel"
      widget: "list"
      fields: 
          - {label: Panel Image, name: panel_image, widget: image }   
          - {label: Title, name: title, widget: string, default: "Default Title"}
          - {label: Display Address, name: display_address, widget: string, default: "535 Mission St. Suite 2600 San Francisco, CA 94105"}
          - {label: Phone Number, name: phone_number, widget: string, default: "default_key"}
          - {label: Email, name: email, widget: string, default: "email@default.com"}
          - {label: Directions Link, name: directions_link, widget: string, default: "https://www.google.com/maps/place/535+Mission+St+%232600,+San+Francisco,+CA+94105/@37.7888907,-122.400289,17z/data=!3m1!4b1!4m5!3m4!1s0x8085806325b00825:0x7808b0fc4ef4d3a6!8m2!3d37.7888907!4d-122.3981003"}
  
